In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns 
from  plotly.offline import iplot
import plotly as py 
import plotly.tools as tls 
import cufflinks as cf 
import plotly.express as px
%matplotlib inline
py.offline.init_notebook_mode(connected=True)
cf.go_offline()
pd.set_option("display.max_columns", None)
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge,Lasso,LassoCV,ElasticNet,ElasticNetCV,LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import statsmodels.formula.api as smf
from pandas_profiling import ProfileReport

In [2]:
df_2015=pd.read_csv("2015.csv")

In [3]:
df_2015.head()

Country          Region  Happiness Rank  Happiness Score  \
0  Switzerland  Western Europe               1            7.587   
1      Iceland  Western Europe               2            7.561   
2      Denmark  Western Europe               3            7.527   
3       Norway  Western Europe               4            7.522   
4       Canada   North America               5            7.427   

   Standard Error  Economy (GDP per Capita)   Family  \
0         0.03411                   1.39651  1.34951   
1         0.04884                   1.30232  1.40223   
2         0.03328                   1.32548  1.36058   
3         0.03880                   1.45900  1.33095   
4         0.03553                   1.32629  1.32261   

   Health (Life Expectancy)  Freedom  Trust (Government Corruption)  \
0                   0.94143  0.66557                        0.41978   
1                   0.94784  0.62877                        0.14145   
2                   0.87464  0.64938                        0.48357   
3                   0.88521  0.66973                        0.36503   
4                   0.90563  0.63297                        0.32957   

   Generosity  Dystopia Residual  
0     0.29678            2.51738  
1     0.43630            2.70201  
2     0.34139            2.49204  
3     0.34699            2.46531  
4     0.45811            2.45176

In [4]:
df_2015.drop(["Country","Region","Happiness Rank"],axis=1,inplace=True)

In [5]:
df_2015["GDP"]=df_2015["Economy (GDP per Capita)"]
df_2015["HP_Score"]=df_2015["Happiness Score"]
df_2015["Trust"]=df_2015["Trust (Government Corruption)"]
df_2015["Health"]=df_2015["Health (Life Expectancy)"]
df_2015["Std_Error"]=df_2015["Standard Error"]
df_2015.drop(["Economy (GDP per Capita)","Health (Life Expectancy)","Trust (Government Corruption)","Std_Error"],axis=1,inplace=True)


In [6]:
df_2015.drop(["Happiness Score"],axis=1,inplace=True)

In [7]:
a=ProfileReport(df_2015)

In [8]:
df_2015

Standard Error   Family  Freedom  Generosity  Dystopia Residual      GDP  \
0           0.03411  1.34951  0.66557     0.29678            2.51738  1.39651   
1           0.04884  1.40223  0.62877     0.43630            2.70201  1.30232   
2           0.03328  1.36058  0.64938     0.34139            2.49204  1.32548   
3           0.03880  1.33095  0.66973     0.34699            2.46531  1.45900   
4           0.03553  1.32261  0.63297     0.45811            2.45176  1.32629   
..              ...      ...      ...         ...                ...      ...   
153         0.03464  0.77370  0.59201     0.22628            0.67042  0.22208   
154         0.03656  0.35386  0.48450     0.18260            1.63328  0.28665   
155         0.05015  0.47489  0.15684     0.47179            0.32858  0.66320   
156         0.08658  0.41587  0.11850     0.19727            1.83302  0.01530   
157         0.06727  0.13995  0.36453     0.16681            1.56726  0.20868   

     HP_Score    Trust   Health  
0       7.587  0.41978  0.94143  
1       7.561  0.14145  0.94784  
2       7.527  0.48357  0.87464  
3       7.522  0.36503  0.88521  
4       7.427  0.32957  0.90563  
..        ...      ...      ...  
153     3.465  0.55191  0.42864  
154     3.340  0.08010  0.31910  
155     3.006  0.18906  0.72193  
156     2.905  0.10062  0.22396  
157     2.839  0.10731  0.28443  

[158 rows x 9 columns]

In [9]:
a.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [10]:
results = smf.ols('HP_Score ~ Family+GDP+Trust+Health+Generosity', data=df_2015).fit()

In [11]:
 print(results.summary())

                            OLS Regression Results                            
Dep. Variable:               HP_Score   R-squared:                       0.760
Model:                            OLS   Adj. R-squared:                  0.752
Method:                 Least Squares   F-statistic:                     96.03
Date:                Mon, 13 Jun 2022   Prob (F-statistic):           3.09e-45
Time:                        15:56:16   Log-Likelihood:                -132.49
No. Observations:                 158   AIC:                             277.0
Df Residuals:                     152   BIC:                             295.4
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      1.9912      0.193     10.300      0.0

In [12]:
y=df_2015[["HP_Score"]]
y

HP_Score
0       7.587
1       7.561
2       7.527
3       7.522
4       7.427
..        ...
153     3.465
154     3.340
155     3.006
156     2.905
157     2.839

[158 rows x 1 columns]

In [13]:
x=df_2015.drop(["HP_Score","Standard Error","Generosity","Dystopia Residual"],axis=1)
x

Family  Freedom      GDP    Trust   Health
0    1.34951  0.66557  1.39651  0.41978  0.94143
1    1.40223  0.62877  1.30232  0.14145  0.94784
2    1.36058  0.64938  1.32548  0.48357  0.87464
3    1.33095  0.66973  1.45900  0.36503  0.88521
4    1.32261  0.63297  1.32629  0.32957  0.90563
..       ...      ...      ...      ...      ...
153  0.77370  0.59201  0.22208  0.55191  0.42864
154  0.35386  0.48450  0.28665  0.08010  0.31910
155  0.47489  0.15684  0.66320  0.18906  0.72193
156  0.41587  0.11850  0.01530  0.10062  0.22396
157  0.13995  0.36453  0.20868  0.10731  0.28443

[158 rows x 5 columns]

In [14]:
x_test,x_train,y_test,y_train=train_test_split(x,y,random_state=10,test_size=0.75)

In [15]:
lr=LinearRegression()

In [16]:
lr.fit(x_train,y_train)

LinearRegression()

In [17]:
lr.coef_

array([[1.20716166, 1.48014898, 0.74762892, 1.15259965, 1.28219818]])

In [18]:
lr.intercept_

array([1.92901006])

In [19]:
lr.fit(x_test,y_test)

LinearRegression()

In [20]:
lr.score(x_test,y_test)

0.7959922679998456

In [21]:
lr.predict([[1.34951,0.66557,1.39651,0.41978,0.94143]])

array([[7.30162267]])